version: 2
updates:
  # Maintain npm / pnpm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: 'chalk'
        update-types: ['version-update:semver-major']
    groups:
      dev-dependencies:
        patterns:
          - '@eslint/*'
          - 'eslint*'
          - 'prettier*'

  # Maintain GitHub Actions workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'monthly'
