title: 'djs-prototype'
description: 'A multipurpose discord bot template'

# URL configuration
url: 'https://rafisarkar0128.github.io'
baseurl: '/djs-prototype'

# Markdown & Code Highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Theme Configuration
remote_theme: pages-themes/hacker@v0.2.0

# Plugins supported natively by GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
